import Head from 'next/head'

export default function Layout({ children }) {
    return (
        <main style={{maxWidth: '360px', margin: 'auto', overflow: 'hidden'}}>
            <Head>
                <title>大爷显灵</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/daye.png" />
            </Head>
            {children}
        </main>
    )
  }