import Head from 'next/head'
import styles from '../styles/Setting.module.css'
import Text from '../components/Text'
import { useRouter } from 'next/router'
import Line from '../components/Line'

export default function Home({playerSlect, playerList, playerListHandler, playerSelectHandler, set, reset, selected, isBasic, setIsBasic}) {

  const router = useRouter()

  return (
    <>
      <Head>
        <title>大爷显灵</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/daye.png" />
      </Head>
      <div className={styles.wrapper}>
            <div style={{position: 'relative', width: '100%', display: 'flex', justifyContent: 'center'}}>
                <div
                    style={{
                        width: '90%',
                        position: 'absolute',
                        fill: 'white'
                    }}
                    className='animate__animated animate__zoomIn animate__delay-3s'
                >
                    <Line />
                </div>
                <div style={{width: '80%', marginBottom: '25px'}} className='animate__animated animate__hinge animate__delay-1s'>
                    <Text />
                </div>
            </div>
            <p className={styles.text + ' animate__animated animate__bounceInLeft'}>按座位顺序选择玩家</p>
            <div className={styles.playerSlectWrapper}>
                {playerSlect.map((player, index) => {
                return (
                    <p key={index} className={styles.player} onClick={() => playerSelectHandler(player)}>
                        {player}
                    </p>
                );
                })}
            </div>
            <p className={styles.text + ' animate__animated animate__bounceInRight'}>选择开始玩家</p>
            <div className={styles.playerSlectWrapper}>
                {playerList.map((player, index) => {
                return (
                    <p key={Math.random()} onClick={() => {playerListHandler(player, index)}} className={selected[index] ? `${styles.player} ${styles.transform}` : `${styles.player} ${styles.opacity}`}>
                    {player}
                    </p>
                )
                })}
            </div>
            <div className='mode-wrapper'>
                <p style={{fontSize: '16px', color: 'white'}}>选择游戏模式: </p>
                <button className={isBasic ? 'mode-select selected' : 'mode-select'} onClick={() => setIsBasic(true)}>基本包</button>
                <button className={isBasic ? 'mode-select' : 'mode-select selected'} onClick={() => setIsBasic(false)}>騎士包</button>
            </div>
            <div className={styles.buttonWrapper}>
                <button className={styles.button} style={{backgroundColor: '#52b788'}} onClick={set}>确定</button>
                <button className={styles.button} style={{backgroundColor: '#fca311'}} onClick={reset}>重置</button>
                <button className={styles.button} style={{backgroundColor: '#dda15e'}} onClick={() => router.push('/List')}>台词列表</button>
                <button className={styles.button} style={{backgroundColor: '#0077b6'}} onClick={() => router.push('/PlayList')}>播放列表</button>
            </div>
        </div>
    </>
  )
}


